root = "/ephemeral/containerd/runsc"
[runsc_config]
debug = "true"
debug-log = "/ephemeral/containerd/runsc-logs.fifo"
panic-log = "/ephemeral/containerd/runsc-logs.fifo"
log = "/ephemeral/containerd/runsc-logs.fifo"
